os:
  - linux

language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

script: 
  - pwd
  - rm -rf  _integration_test
  - mkdir _integration_test
  - cd _integration_test
  - pwd
  - npm install --save --save-dev --save-exact
  - npm run test

notifications:
  email:
    on_success: never
    on_failure: change
